dateModified: 1746715053
email:
  fromEmail: anuar@heyblackmagic.com
  fromName: Foundation
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/uploads/images'
    type: craft\fs\Local
    url: '@url/uploads/images'
meta:
  __names__:
    c4f1af9d-b96d-45b6-b918-22715d89be7a: Images # Images
    e179b363-8cfe-41ca-ac5d-d902d2cb7eff: Foundation # Foundation
    fff667bf-7fe7-4ddb-96b6-fdd705423387: Foundation # Foundation
plugins:
  image-optimize:
    edition: standard
    enabled: true
    licenseKey: LQI39I78TN4K70RIQXVZ5L3E
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 6Z40HLW3WLSF0ULSS1U0P8AI
    schemaVersion: 3.0.12
  templatecomments:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: Foundation
  schemaVersion: 5.7.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
