dateModified: 1677047311
email:
  fromEmail: anuar@hey.com
  fromName: Foundation
  transportType: craft\mail\transportadapters\Sendmail
fs:
  media:
    hasUrls: true
    name: Media
    settings:
      path: '@filesystemMediaPath'
    type: craft\fs\Local
    url: '@filesystemMediaUrl'
meta:
  __names__:
    700b7e8f-d346-4c21-aca8-6c9ee985cd77: Foundation # Foundation
    2507e5aa-62d0-4d14-8335-6e74e5041053: Foundation # Foundation
    498798d1-e97a-4db6-bc4f-3228b8c51881: Common # Common
    acf8b0db-5f3a-4dfd-be93-415733620f18: Images # Images
plugins:
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  quick-field:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
system:
  edition: solo
  live: true
  name: Foundation
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
